### PR TITLE
feat: add blog & first blog post

### PR DESCRIPTION
**Pull request by xynydev**
This PR adds blog functionality with an introductory blog post to the site. The blog post should be written and ready before the repositories are moved from Universal Blue, along with a PR cleaning up th Universal Blue website and a shorter blog post that mirrors this one. 

Here's a screenshot of the current state:

image

### CODE REVIEW

**Comment by fiftydinar** [comment]
It would be nice to have date of the blog sorted in left pane behind "All posts"

**Comment by xynydev** [comment]
> It would be nice to have date of the blog sorted in left pane behind "All posts"
> So newest would show 1st

Thanks! That's implemented on the blog front page, but forgot it in the sidebar.
image

**Comment by xynydev** [comment]
image

**Comment by xynydev** [comment]
I first set out to document all possible migration paths, but now I'm not certain if "Create a new repository" should be included at all. I thought it would be the "lazy option" but it sounds way harder than the other one and has more cons.

**Comment by xynydev** [comment]
> What are the cons with "Create a new repository" approach

Listed in the draft post

**Comment by xynydev** [comment]
Ok, the post doesn't have any glaring TODOs now, so I won't have to stress about that anymore. I wrote some general info in the OIDC section. I'd still like to have others review a bit of what I'm writing here.

**Comment by xynydev** [comment]
I replaced the URLs now ([b3fca65](https://github.com/blue-build/website/pull/28/commits/b3fca659d11f8d40957a4904f43a053c12e2ea7b)), so the PR is ready to merge whenever everything else is, once I get some comments ofc. This will cause builds to fail, but they should start working again once the repos are moved.

**Pull request merged**
